### ISSUE TITLE
Installation issue at the downloading additional dependencies step

### ISSUE THREAD

**Issue by AppWick-hub** [opain/GenoPred#114]
Dear Developers of GenoPred,
When I try to install GenoPred through miniconda3, some error occurred, which has been fixed after I installed through miniforge3. But at the step 3, when I try to download dependencies using:

snakemake -j 5 --use-conda --conda-frontend mamba install_r_packages

I am getting errors as following: 

Error in rule install_lassosum: 
jobid: 2
.
.

Error in rule install_ggchicklet: 
...

Error in rule install_genoutils: 
....

Any advices?

Best 
A

**Comment by opain** [comment]
Hello, 

Thank you for the feedback that installation via miniforge is working better than miniconda. This is congruent with other peoples experience. I will update the instructions ASAP.

Strange that you are facing errors with the installation of R packages. Are there any additional logs produced? In your post, it just shows '...'? Please send screenshots or full logs.

If you are working on an HPC, you will need to run this command on a compute node, not the login node, otherwise the HPC might be killing the jobs. Another issue might be that you have loaded another version of R before running the snakemake command. Make sure you are working in a clean environment. 

If you can provide more log information, I can give more specific advice.

Best wishes,

Ollie

**Comment by AppWick-hub** [comment]
Hi,
I am working on HPC and I have tried this command with/without a compute node. But the error occurring is similar. Below is a more detailed screenshot of the error:

![genopred_errors](https://github.com/user-attachments/assets/94ed70fb-4778-4924-b2c5-37152056e0ec)

**Comment by opain** [comment]
Thank you for the screenshot.

Each job/rule creates its own log file. For example, resources/data/logs/install_genoutils.log. Have you looked at those files? Please send one of them to me and it will hopefully tell us why it is failing.

Best wishes,

Ollie

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AppWick-hub** [comment]
Hey, 

Unfortunately I won't be able to extract the log file from the server due to restrictions. But here are the screenshots from the log file below:

![genopred_errors 2](https://github.com/user-attachments/assets/32fa68e2-d5fe-40f5-9a7c-e6ea70ff8b15)
![genopred_errors 3](https://github.com/user-attachments/assets/6a0034b8-9b8e-4eb8-b353-b483a213e6ab)

**Comment by opain** [comment]
This is the same output as before. Can you send me a screenshot showing the contents of the log files from a given rule? E.g. resources/data/logs/install_genoutils.log. You can print the contents of the log file to the screen by using the less or more functions?

**Comment by AppWick-hub** [comment]
All the generated log files (e.g., install_lassosum.log, install_ggchicklet.log, and install_genoutils.log) contain the same error message as attached below: 

![genopred_errors 4](https://github.com/user-attachments/assets/321a9088-48f1-45df-ae0a-a27ecefa5f6d)

**Comment by opain** [comment]
Thank you. I have not seen this issue before, which probably means it is due to some security restraints specific to your HPC. I would suggest contacting your HPC helpdesk to ask for advice. Explain to them that this is the error your receive when trying to install an R package from GitHub using the devtools package.

Otherwise, the solution would be to temporarily disable the SSL certificate verification (I think the HPC admins would disapprove of this solution). But if you do want to go down this road, follow these steps:

```
# Activate the conda environment (the full path has been blanked out)
conda activate .snakemake/conda/2a7d42b3la1817a95cea0527e449bae_

# Open R
R

# Disable SSL certificate check
Sys.setenv(GIT_SSL_NO_VERIFY = TRUE)

# Install R packages
remotes::install_github(\"hrbrmstr/ggchicklet@64c468dd0900153be1690dbfc5cfb35710da8183\")
remotes::install_github(\"tshmak/lassosum@v0.4.5\")
devtools::install_github(\"opain/GenoUtils@50ac8a2078226c8c2349064f904031576fbfe606\")

# Exit R without saving workspace
q()
n

# Deactivate conda environment
source ~/.bashrc

# Activate GenoPred environment
conda activate genopred

# Touch outputs for install_r_packages rule
snakemake -t -j1 --use-conda install_r_packages
```

Once you have done this, you should be able to use the pipeline as normal.
