### ISSUE TITLE
Preparation resources

### ISSUE THREAD

**Issue by AndreaConti0** [opain/GenoPred#65]
Hi, I don't know if something in my analysis go wrong but I think that it could be simplier if you would introduce  in the gz folder test_data/target/imputed_sample_bgen/ the index for every chromosome file (in my case the absence of these files cause a crash of the GenoPredPipe).

Another thing ... I think that you can specified in step 2 of the "getting starded" point, the installation of ghostscript package
`sudo apt-get update`
`sudo apt-get ghostscript`
... because someone could haven't it, but the R function bitmap() require the presence of ghostscript.

Maybe, I could be wrong, but in case I'm waiting for news.

**Comment by opain** [comment]
Hello,

Apologies, the requirement for .bgi files for bgen format is new and I have not been able to update the test_data yet due to very slow upload speeds to zenodo (I don't know why). Hopefully I will be able to make the upload in the next few days.

Thank you for highlighting the need for ghostscript. I will make a note of this in the README.

**Comment by opain** [comment]
This has now been resolved in the latest push.
